### ISSUE TITLE
eggs spawning in inventory

### ISSUE THREAD

**Issue by thecloudking** [SmoochyPit/Warp-Pads-Rewrite#5]
immediately upon generating a world with this datapack enabled, warp pad spawn eggs started spawning in my inventory every few seconds. so frequently that it's been less than a minute since i started generating the world, and i already have about half a stack of tier 1, tier 2, and tier 3 warp pad eggs
![2022-06-08_19 03 54](https://user-images.githubusercontent.com/96870182/172748533-ccae1172-02aa-4bb5-94c2-47785a0bb1cb.png)

**Comment by inventor200** [comment]
If you are playing with the Hermitcraft datapack that unlocks all recipes on start, it will cause this problem.

**Comment by Dragonruler6008** [comment]
Can confirm that having that datapack is the issue. (1.19) Having the Vanilla Tweaks datapack that unlocks all the recipes causes the warp pad datapack to give the items to the player on a continuous cycle. (about every 2ish seconds.) 

I did note that whenever you received the eggs, the All Recipes datapack restarted and ran itself again thus giving you another set and triggering the cycle.

Here is the exact Vanilla Tweaks datapack that is causing the issue.
[unlock all recipes v2.0.4.zip](https://github.com/SmoochyPit/Warp-Pads-Rewrite/files/8872526/unlock.all.recipes.v2.0.4.zip)

**Comment by SmoochyPit** [comment]
"Unlock All Recipes" data packs will trigger crafting recipes with custom results. This is an incompatibility that I cannot do anything about. That particular "Unlock All Recipes" datapack has an especially poor design by triggering constantly rather than just when a player joins, so there's not any way for me or a player to even mitigate the issue, either.

Anyways, that data pack is incompatible with Warp Pads, unless you manually remove the crafting recipes from the pack (detailed in `config.tdn`).

**Comment by SmoochyPit** [comment]
https://github.com/SmoochyPit/Recipe-Unlock

I threw this together-- This will unlock all recipes for players *without* causing this issue. This pack should be compatible with other data packs utilizing custom crafting recipes. 

**DO NOT install this on existing worlds without putting your inventory in a chest**! This will remove all items in your inventory when it is installed!
